name: 'ESLint Issue Repro Snippet'
description: 'Enforce code repro requirements on posted issues by running eslint'
author: 'Miklós Fazekas'

runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  error-label:
    description: "The label to add to the issue if the code doesn't pass the linter"
    required: true
    default: 'error-in-repro-code'
  eslint-config:
    description: 'The eslint config to use'
    required: true
    default: |
      {
        root: true,
        env: {
          browser: true,
          es2021: true,
        },
        extends: 'plugin:react/recommended',
        overrides: [],
        parserOptions: {
          ecmaVersion: 'latest',
          sourceType: 'module',
        },
        settings: {
          react: {
            version: '17.0.2',
          },
        }
