# Sample workflow demonstrating how to use this action
name: IssueCheck

on:
  issues:
    types: [opened, edited]

jobs:
  check-issue-example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          name: ${{ github.event.issue.user.login }}
